### ISSUE TITLE
Start using Issues?

### ISSUE THREAD

**Issue by markdreed512** [BaltimoreCode-Coffee/OldWebsite#17]
I'd love to contribute to the site, but I'm not sure what feature I should tackle. I'd hate to be working on something that someone else is working on at the same time. Any interest in using this feature to keep track of what features need implementing and who is taking them on?

**Comment by juliancoy** [comment]
Good idea! At least we can try it out for a while. I'll open one

**Comment by juliancoy** [comment]
Issues have been implemented
